/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import modelo.dao.SelecoesDAO;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.util.Vector;


/**
 *
 * @author Gustavo
 */
public class CriarGruposManual extends javax.swing.JFrame {

    /**
     * Creates new form CriarGruposManual
     */
    public CriarGruposManual() {

        initComponents();
        this.setLocationRelativeTo(null);
        restaurarDadosSelecoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        grupoE = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        selecaoDezenove = new javax.swing.JComboBox<>();
        selecaoVinte = new javax.swing.JComboBox<>();
        selecaoDezessete = new javax.swing.JComboBox<>();
        selecaoDezoito = new javax.swing.JComboBox<>();
        grupoH = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        selecaoTrintaUm = new javax.swing.JComboBox<>();
        selecaoVinteNove = new javax.swing.JComboBox<>();
        selecaoTrinta = new javax.swing.JComboBox<>();
        selecaoTrintaDois = new javax.swing.JComboBox<>();
        grupoD = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        selecaoDezesseis = new javax.swing.JComboBox<>();
        selecaoTreze = new javax.swing.JComboBox<>();
        selecaoQuatorze = new javax.swing.JComboBox<>();
        selecaoQuinze = new javax.swing.JComboBox<>();
        grupoB = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        selecaoOito = new javax.swing.JComboBox<>();
        selecaoCinco = new javax.swing.JComboBox<>();
        selecaoSeis = new javax.swing.JComboBox<>();
        selecaoSete = new javax.swing.JComboBox<>();
        grupoG = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        selecaoVinteSeis = new javax.swing.JComboBox<>();
        selecaoVinteCinco = new javax.swing.JComboBox<>();
        selecaoVinteSete = new javax.swing.JComboBox<>();
        selecaoVinteOito = new javax.swing.JComboBox<>();
        grupoF = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        selecaoVinteUm = new javax.swing.JComboBox<>();
        selecaoVinteQuatro = new javax.swing.JComboBox<>();
        selecaoVinteDois = new javax.swing.JComboBox<>();
        selecaoVinteTreis = new javax.swing.JComboBox<>();
        grupoA = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        selecaoUm = new javax.swing.JComboBox<>();
        selecaoTres = new javax.swing.JComboBox<>();
        selecaoDois = new javax.swing.JComboBox<>();
        selecaoQuatro = new javax.swing.JComboBox<>();
        grupoC = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        selecaoOnze = new javax.swing.JComboBox<>();
        selecaoDez = new javax.swing.JComboBox<>();
        selecaoNove = new javax.swing.JComboBox<>();
        selecaoDoze = new javax.swing.JComboBox<>();
        salvar1 = new code.botao();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Criar Grupos Manualmente");
        setBackground(new java.awt.Color(51, 51, 51));
        setResizable(false);

        jPanel11.setBackground(new java.awt.Color(51, 51, 51));

        jPanel12.setBackground(new java.awt.Color(51, 51, 51));
        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("Ubuntu Mono", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/world-cup.png"))); // NOI18N
        jLabel9.setText("Grupos Copa Do Mundo 2022");
        jLabel9.setToolTipText("");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        grupoE.setBackground(new java.awt.Color(51, 51, 51));
        grupoE.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        grupoE.setPreferredSize(new java.awt.Dimension(170, 216));

        jLabel22.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("GRUPO E");

        selecaoDezenove.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N

        selecaoVinte.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N

        selecaoDezessete.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N

        selecaoDezoito.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N

        javax.swing.GroupLayout grupoELayout = new javax.swing.GroupLayout(grupoE);
        grupoE.setLayout(grupoELayout);
        grupoELayout.setHorizontalGroup(
            grupoELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupoELayout.createSequentialGroup()
                .addGroup(grupoELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(grupoELayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel22))
                    .addGroup(grupoELayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(grupoELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selecaoVinte, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selecaoDezoito, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selecaoDezenove, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selecaoDezessete, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        grupoELayout.setVerticalGroup(
            grupoELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupoELayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addComponent(selecaoDezessete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selecaoDezoito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selecaoDezenove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selecaoVinte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        grupoH.setBackground(new java.awt.Color(51, 51, 51));
        grupoH.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        grupoH.setPreferredSize(new java.awt.Dimension(170, 216));

        jLabel37.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("GRUPO H");

        selecaoTrintaUm.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N

        selecaoVinteNove.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N

        selecaoTrinta.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N

        selecaoTrintaDois.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N

        javax.swing.GroupLayout grupoHLayout = new javax.swing.GroupLayout(grupoH);
        grupoH.setLayout(grupoHLayout);
        grupoHLayout.setHorizontalGroup(
            grupoHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupoHLayout.createSequentialGroup()
                .addGroup(grupoHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(grupoHLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel37))
                    .addGroup(grupoHLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(grupoHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selecaoTrintaDois, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selecaoTrinta, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selecaoTrintaUm, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selecaoVinteNove, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        grupoHLayout.setVerticalGroup(
            grupoHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupoHLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel37)
                .addGap(18, 18, 18)
                .addComponent(selecaoVinteNove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selecaoTrinta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selecaoTrintaUm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selecaoTrintaDois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        grupoD.setBackground(new java.awt.Color(51, 51, 51));
        grupoD.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        grupoD.setPreferredSize(new java.awt.Dimension(170, 216));

        jLabel17.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("GRUPO D");

        selecaoDezesseis.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N

        selecaoTreze.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N

        selecaoQuatorze.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N

        selecaoQuinze.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N

        javax.swing.GroupLayout grupoDLayout = new javax.swing.GroupLayout(grupoD);
        grupoD.setLayout(grupoDLayout);
        grupoDLayout.setHorizontalGroup(
            grupoDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupoDLayout.createSequentialGroup()
                .addGroup(grupoDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(grupoDLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel17))
                    .addGroup(grupoDLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(grupoDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selecaoDezesseis, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selecaoQuatorze, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selecaoQuinze, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selecaoTreze, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        grupoDLayout.setVerticalGroup(
            grupoDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupoDLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(selecaoTreze, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selecaoQuatorze, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selecaoQuinze, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selecaoDezesseis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        grupoB.setBackground(new java.awt.Color(51, 51, 51));
        grupoB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        grupoB.setPreferredSize(new java.awt.Dimension(170, 216));

        jLabel7.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("GRUPO B");

        selecaoOito.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N

        selecaoCinco.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N

        selecaoSeis.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N

        selecaoSete.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N

        javax.swing.GroupLayout grupoBLayout = new javax.swing.GroupLayout(grupoB);
        grupoB.setLayout(grupoBLayout);
        grupoBLayout.setHorizontalGroup(
            grupoBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupoBLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, grupoBLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(grupoBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selecaoOito, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selecaoSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selecaoSete, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selecaoCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        grupoBLayout.setVerticalGroup(
            grupoBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupoBLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(selecaoCinco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selecaoSeis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selecaoSete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selecaoOito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        grupoG.setBackground(new java.awt.Color(51, 51, 51));
        grupoG.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        grupoG.setPreferredSize(new java.awt.Dimension(170, 216));

        jLabel32.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("GRUPO G");

        selecaoVinteSeis.setEditable(true);
        selecaoVinteSeis.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N

        selecaoVinteCinco.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N

        selecaoVinteSete.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N

        selecaoVinteOito.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N

        javax.swing.GroupLayout grupoGLayout = new javax.swing.GroupLayout(grupoG);
        grupoG.setLayout(grupoGLayout);
        grupoGLayout.setHorizontalGroup(
            grupoGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupoGLayout.createSequentialGroup()
                .addGroup(grupoGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(grupoGLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel32))
                    .addGroup(grupoGLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(grupoGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selecaoVinteOito, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selecaoVinteSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selecaoVinteSete, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selecaoVinteCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        grupoGLayout.setVerticalGroup(
            grupoGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupoGLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel32)
                .addGap(18, 18, 18)
                .addComponent(selecaoVinteCinco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selecaoVinteSeis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selecaoVinteSete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selecaoVinteOito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        grupoF.setBackground(new java.awt.Color(51, 51, 51));
        grupoF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        grupoF.setPreferredSize(new java.awt.Dimension(170, 216));

        jLabel27.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("GRUPO F");

        selecaoVinteUm.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N

        selecaoVinteQuatro.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N

        selecaoVinteDois.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N

        selecaoVinteTreis.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N

        javax.swing.GroupLayout grupoFLayout = new javax.swing.GroupLayout(grupoF);
        grupoF.setLayout(grupoFLayout);
        grupoFLayout.setHorizontalGroup(
            grupoFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupoFLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel27)
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, grupoFLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(grupoFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selecaoVinteQuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selecaoVinteDois, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selecaoVinteTreis, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selecaoVinteUm, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        grupoFLayout.setVerticalGroup(
            grupoFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupoFLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel27)
                .addGap(18, 18, 18)
                .addComponent(selecaoVinteUm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selecaoVinteDois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selecaoVinteTreis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selecaoVinteQuatro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        grupoA.setBackground(new java.awt.Color(51, 51, 51));
        grupoA.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        grupoA.setPreferredSize(new java.awt.Dimension(170, 216));

        jLabel1.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GRUPO A");

        selecaoUm.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        selecaoUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecaoUmActionPerformed(evt);
            }
        });

        selecaoTres.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        selecaoTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecaoTresActionPerformed(evt);
            }
        });

        selecaoDois.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N

        selecaoQuatro.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N

        javax.swing.GroupLayout grupoALayout = new javax.swing.GroupLayout(grupoA);
        grupoA.setLayout(grupoALayout);
        grupoALayout.setHorizontalGroup(
            grupoALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupoALayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(grupoALayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(grupoALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selecaoQuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selecaoDois, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selecaoTres, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selecaoUm, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        grupoALayout.setVerticalGroup(
            grupoALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupoALayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(selecaoUm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selecaoDois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selecaoTres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selecaoQuatro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        grupoC.setBackground(new java.awt.Color(51, 51, 51));
        grupoC.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        grupoC.setPreferredSize(new java.awt.Dimension(170, 216));

        jLabel12.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("GRUPO C");

        selecaoOnze.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N

        selecaoDez.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N

        selecaoNove.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        selecaoNove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecaoNoveActionPerformed(evt);
            }
        });

        selecaoDoze.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N

        javax.swing.GroupLayout grupoCLayout = new javax.swing.GroupLayout(grupoC);
        grupoC.setLayout(grupoCLayout);
        grupoCLayout.setHorizontalGroup(
            grupoCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupoCLayout.createSequentialGroup()
                .addGroup(grupoCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(grupoCLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel12))
                    .addGroup(grupoCLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(grupoCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selecaoDoze, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selecaoDez, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selecaoOnze, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selecaoNove, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        grupoCLayout.setVerticalGroup(
            grupoCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupoCLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(selecaoNove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selecaoDez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selecaoOnze, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selecaoDoze, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        salvar1.setForeground(new java.awt.Color(255, 0, 0));
        salvar1.setText("SALVAR");
        salvar1.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
        salvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(salvar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(grupoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grupoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(grupoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grupoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(grupoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grupoG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(grupoD, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(grupoH, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(grupoB, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grupoA, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(grupoE, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grupoF, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(grupoD, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grupoC, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(grupoH, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grupoG, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(salvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selecaoUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecaoUmActionPerformed

    }//GEN-LAST:event_selecaoUmActionPerformed

    private void salvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salvar1ActionPerformed

    private void selecaoTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecaoTresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selecaoTresActionPerformed

    private void selecaoNoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecaoNoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selecaoNoveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriarGruposManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriarGruposManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriarGruposManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriarGruposManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriarGruposManual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel grupoA;
    private javax.swing.JPanel grupoB;
    private javax.swing.JPanel grupoC;
    private javax.swing.JPanel grupoD;
    private javax.swing.JPanel grupoE;
    private javax.swing.JPanel grupoF;
    private javax.swing.JPanel grupoG;
    private javax.swing.JPanel grupoH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private code.botao salvar1;
    private javax.swing.JComboBox<String> selecaoCinco;
    private javax.swing.JComboBox<String> selecaoDez;
    private javax.swing.JComboBox<String> selecaoDezenove;
    private javax.swing.JComboBox<String> selecaoDezesseis;
    private javax.swing.JComboBox<String> selecaoDezessete;
    private javax.swing.JComboBox<String> selecaoDezoito;
    private javax.swing.JComboBox<String> selecaoDois;
    private javax.swing.JComboBox<String> selecaoDoze;
    private javax.swing.JComboBox<String> selecaoNove;
    private javax.swing.JComboBox<String> selecaoOito;
    private javax.swing.JComboBox<String> selecaoOnze;
    private javax.swing.JComboBox<String> selecaoQuatorze;
    private javax.swing.JComboBox<String> selecaoQuatro;
    private javax.swing.JComboBox<String> selecaoQuinze;
    private javax.swing.JComboBox<String> selecaoSeis;
    private javax.swing.JComboBox<String> selecaoSete;
    private javax.swing.JComboBox<String> selecaoTres;
    private javax.swing.JComboBox<String> selecaoTreze;
    private javax.swing.JComboBox<String> selecaoTrinta;
    private javax.swing.JComboBox<String> selecaoTrintaDois;
    private javax.swing.JComboBox<String> selecaoTrintaUm;
    private javax.swing.JComboBox<Object> selecaoUm;
    private javax.swing.JComboBox<String> selecaoVinte;
    private javax.swing.JComboBox<String> selecaoVinteCinco;
    private javax.swing.JComboBox<String> selecaoVinteDois;
    private javax.swing.JComboBox<String> selecaoVinteNove;
    private javax.swing.JComboBox<String> selecaoVinteOito;
    private javax.swing.JComboBox<String> selecaoVinteQuatro;
    private javax.swing.JComboBox<String> selecaoVinteSeis;
    private javax.swing.JComboBox<String> selecaoVinteSete;
    private javax.swing.JComboBox<String> selecaoVinteTreis;
    private javax.swing.JComboBox<String> selecaoVinteUm;
    // End of variables declaration//GEN-END:variables

    
    public void restaurarDadosSelecoes() {

        try {
            SelecoesDAO objselecao = new SelecoesDAO();
            
            ResultSet rs = objselecao.selecoes();
            while (rs.next()) {
               
                
                
                selecaoUm.addItem(rs.getString(2));
                selecaoDois.addItem(rs.getString(2));
                selecaoTres.addItem(rs.getString(2));
                selecaoQuatro.addItem(rs.getString(2));
                selecaoCinco.addItem(rs.getString(2));
                selecaoSeis.addItem(rs.getString(2));
                selecaoSete.addItem(rs.getString(2));
                selecaoOito.addItem(rs.getString(2));
                selecaoNove.addItem(rs.getString(2));
                selecaoDez.addItem(rs.getString(2));
                selecaoOnze.addItem(rs.getString(2));
                selecaoDoze.addItem(rs.getString(2));
                selecaoTreze.addItem(rs.getString(2));
                selecaoQuatorze.addItem(rs.getString(2));
                selecaoQuinze.addItem(rs.getString(2));
                selecaoDezesseis.addItem(rs.getString(2));
                selecaoDezessete.addItem(rs.getString(2));
                selecaoDezoito.addItem(rs.getString(2));
                selecaoDezenove.addItem(rs.getString(2));
                selecaoVinte.addItem(rs.getString(2));
                selecaoVinteUm.addItem(rs.getString(2));
                selecaoVinteDois.addItem(rs.getString(2));
                selecaoVinteTreis.addItem(rs.getString(2));
                selecaoVinteQuatro.addItem(rs.getString(2));
                selecaoVinteCinco.addItem(rs.getString(2));
                selecaoVinteSeis.addItem(rs.getString(2));
                selecaoVinteSete.addItem(rs.getString(2));
                selecaoVinteOito.addItem(rs.getString(2));
                selecaoVinteNove.addItem(rs.getString(2));
                selecaoTrinta.addItem(rs.getString(2));
                selecaoTrintaUm.addItem(rs.getString(2));
                selecaoTrintaDois.addItem(rs.getString(2));

            }

        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "carregar bdd" + erro);
        }
    }

}
