/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import modelo.dao.SelecoesDAO;
import modelo.dto.SelecoesDTO;
import code.SimulacaoCode;

/**
 *
 * @author Gustavo
 */
public class Simulacao extends javax.swing.JFrame {

   
    public Simulacao() {
        initComponents();
        this.setLocationRelativeTo(null);
        GrupoOficial();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoG = new javax.swing.JPanel();
        G = new javax.swing.JLabel();
        brasil = new javax.swing.JLabel();
        servia = new javax.swing.JLabel();
        suica = new javax.swing.JLabel();
        camaroes = new javax.swing.JLabel();
        semifinal2 = new javax.swing.JPanel();
        semifinalBUm = new javax.swing.JLabel();
        semifinalBDois = new javax.swing.JLabel();
        grupoD = new javax.swing.JPanel();
        D = new javax.swing.JLabel();
        franca = new javax.swing.JLabel();
        australia = new javax.swing.JLabel();
        dinamarca = new javax.swing.JLabel();
        tunisia = new javax.swing.JLabel();
        grupoH = new javax.swing.JPanel();
        H = new javax.swing.JLabel();
        portugual = new javax.swing.JLabel();
        gana = new javax.swing.JLabel();
        uruguai = new javax.swing.JLabel();
        coreiaDoSul = new javax.swing.JLabel();
        quartas3 = new javax.swing.JPanel();
        quartasCUm = new javax.swing.JLabel();
        quartasCDois = new javax.swing.JLabel();
        final1 = new javax.swing.JPanel();
        finalTimeUm = new javax.swing.JLabel();
        finalTimeDois = new javax.swing.JLabel();
        grupoA = new javax.swing.JPanel();
        A = new javax.swing.JLabel();
        qatar = new javax.swing.JLabel();
        equador = new javax.swing.JLabel();
        senegal = new javax.swing.JLabel();
        holanda = new javax.swing.JLabel();
        oitavas7 = new javax.swing.JPanel();
        oitavasGrupoG1 = new javax.swing.JLabel();
        oitavasGrupoG2 = new javax.swing.JLabel();
        grupoE = new javax.swing.JPanel();
        E = new javax.swing.JLabel();
        espanha = new javax.swing.JLabel();
        costaRica = new javax.swing.JLabel();
        alemanha = new javax.swing.JLabel();
        japao = new javax.swing.JLabel();
        oitavas3 = new javax.swing.JPanel();
        oitavasGrupoC1 = new javax.swing.JLabel();
        oitavasGrupoC2 = new javax.swing.JLabel();
        quartas4 = new javax.swing.JPanel();
        quartasDUm = new javax.swing.JLabel();
        quartasDDois = new javax.swing.JLabel();
        oitavas8 = new javax.swing.JPanel();
        oitavasGrupoH1 = new javax.swing.JLabel();
        oitavasGrupoH2 = new javax.swing.JLabel();
        oitavas4 = new javax.swing.JPanel();
        oitavasGrupoD1 = new javax.swing.JLabel();
        oitavasGrupoD2 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        grupoB = new javax.swing.JPanel();
        B = new javax.swing.JLabel();
        inglaterra = new javax.swing.JLabel();
        ira = new javax.swing.JLabel();
        usa = new javax.swing.JLabel();
        gales = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel116 = new javax.swing.JLabel();
        grupoF = new javax.swing.JPanel();
        F = new javax.swing.JLabel();
        belgica = new javax.swing.JLabel();
        canada = new javax.swing.JLabel();
        marracos = new javax.swing.JLabel();
        croacia = new javax.swing.JLabel();
        jLabel117 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel118 = new javax.swing.JLabel();
        sair = new code.Botao();
        simular = new javax.swing.JButton();
        quartas1 = new javax.swing.JPanel();
        quartasAUm = new javax.swing.JLabel();
        quartasADois = new javax.swing.JLabel();
        semifinal1 = new javax.swing.JPanel();
        semifinalAUm = new javax.swing.JLabel();
        semifinalADois = new javax.swing.JLabel();
        grupoC = new javax.swing.JPanel();
        C = new javax.swing.JLabel();
        argentina = new javax.swing.JLabel();
        arabiaSaudita = new javax.swing.JLabel();
        mexico = new javax.swing.JLabel();
        polonia = new javax.swing.JLabel();
        oitavas5 = new javax.swing.JPanel();
        oitavasGrupoE1 = new javax.swing.JLabel();
        oitavasGrupoE2 = new javax.swing.JLabel();
        oitavas1 = new javax.swing.JPanel();
        oitavasGrupoA1 = new javax.swing.JLabel();
        oitavasGrupoA2 = new javax.swing.JLabel();
        quartas2 = new javax.swing.JPanel();
        quartasBUm = new javax.swing.JLabel();
        quartasBDois = new javax.swing.JLabel();
        oitavas6 = new javax.swing.JPanel();
        oitavasGrupoF1 = new javax.swing.JLabel();
        oitavasGrupoF2 = new javax.swing.JLabel();
        oitavas2 = new javax.swing.JPanel();
        oitavasGrupoB1 = new javax.swing.JLabel();
        oitavasGrupoB2 = new javax.swing.JLabel();
        campeao = new javax.swing.JPanel();
        timeCampeao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        grupoG.setBackground(new java.awt.Color(51, 51, 51));
        grupoG.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        grupoG.setPreferredSize(new java.awt.Dimension(170, 216));

        G.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        G.setForeground(new java.awt.Color(255, 255, 255));
        G.setText("G");

        brasil.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        brasil.setForeground(new java.awt.Color(255, 255, 255));
        brasil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seleções/brazil_icon_127818.png"))); // NOI18N

        servia.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        servia.setForeground(new java.awt.Color(255, 255, 255));
        servia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seleções/serbia_icon_127829.png"))); // NOI18N

        suica.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        suica.setForeground(new java.awt.Color(255, 255, 255));
        suica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seleções/switzerland_icon_127871.png"))); // NOI18N

        camaroes.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        camaroes.setForeground(new java.awt.Color(255, 255, 255));
        camaroes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seleções/cameroon_icon_127792.png"))); // NOI18N

        javax.swing.GroupLayout grupoGLayout = new javax.swing.GroupLayout(grupoG);
        grupoG.setLayout(grupoGLayout);
        grupoGLayout.setHorizontalGroup(
            grupoGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupoGLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(grupoGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(brasil)
                    .addComponent(camaroes)
                    .addComponent(servia)
                    .addComponent(suica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(G)
                .addGap(17, 17, 17))
        );
        grupoGLayout.setVerticalGroup(
            grupoGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupoGLayout.createSequentialGroup()
                .addGroup(grupoGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(grupoGLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(G))
                    .addGroup(grupoGLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(brasil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(servia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(suica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(camaroes)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        semifinal2.setBackground(new java.awt.Color(51, 51, 51));
        semifinal2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        semifinal2.setPreferredSize(new java.awt.Dimension(170, 216));

        semifinalBUm.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        semifinalBUm.setForeground(new java.awt.Color(255, 255, 255));

        semifinalBDois.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        semifinalBDois.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout semifinal2Layout = new javax.swing.GroupLayout(semifinal2);
        semifinal2.setLayout(semifinal2Layout);
        semifinal2Layout.setHorizontalGroup(
            semifinal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(semifinal2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(semifinal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(semifinalBUm)
                    .addComponent(semifinalBDois))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        semifinal2Layout.setVerticalGroup(
            semifinal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, semifinal2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(semifinalBUm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(semifinalBDois)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        grupoD.setBackground(new java.awt.Color(51, 51, 51));
        grupoD.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        grupoD.setPreferredSize(new java.awt.Dimension(170, 216));

        D.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        D.setForeground(new java.awt.Color(255, 255, 255));
        D.setText("D");

        franca.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        franca.setForeground(new java.awt.Color(255, 255, 255));
        franca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seleções/france_icon_127830.png"))); // NOI18N

        australia.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        australia.setForeground(new java.awt.Color(255, 255, 255));
        australia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seleções/australia_icon_127744.png"))); // NOI18N

        dinamarca.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        dinamarca.setForeground(new java.awt.Color(255, 255, 255));
        dinamarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seleções/denmark_icon_127836.png"))); // NOI18N

        tunisia.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        tunisia.setForeground(new java.awt.Color(255, 255, 255));
        tunisia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seleções/tunisia_icon_127788.png"))); // NOI18N

        javax.swing.GroupLayout grupoDLayout = new javax.swing.GroupLayout(grupoD);
        grupoD.setLayout(grupoDLayout);
        grupoDLayout.setHorizontalGroup(
            grupoDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupoDLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(D)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(grupoDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(australia)
                    .addComponent(franca)
                    .addComponent(dinamarca)
                    .addComponent(tunisia))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        grupoDLayout.setVerticalGroup(
            grupoDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupoDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(franca)
                .addGroup(grupoDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(grupoDLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(australia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dinamarca))
                    .addGroup(grupoDLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(D)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tunisia)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        grupoH.setBackground(new java.awt.Color(51, 51, 51));
        grupoH.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        grupoH.setPreferredSize(new java.awt.Dimension(170, 216));

        H.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        H.setForeground(new java.awt.Color(255, 255, 255));
        H.setText("H");

        portugual.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        portugual.setForeground(new java.awt.Color(255, 255, 255));
        portugual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seleções/portugal_icon_127827.png"))); // NOI18N

        gana.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        gana.setForeground(new java.awt.Color(255, 255, 255));
        gana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seleções/ghana_icon_127776.png"))); // NOI18N

        uruguai.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        uruguai.setForeground(new java.awt.Color(255, 255, 255));
        uruguai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seleções/uyuruguayflag_111803.png"))); // NOI18N

        coreiaDoSul.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        coreiaDoSul.setForeground(new java.awt.Color(255, 255, 255));
        coreiaDoSul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seleções/south_korea_icon_127918.png"))); // NOI18N

        javax.swing.GroupLayout grupoHLayout = new javax.swing.GroupLayout(grupoH);
        grupoH.setLayout(grupoHLayout);
        grupoHLayout.setHorizontalGroup(
            grupoHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupoHLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(grupoHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(grupoHLayout.createSequentialGroup()
                        .addGroup(grupoHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(portugual)
                            .addComponent(coreiaDoSul))
                        .addContainerGap(106, Short.MAX_VALUE))
                    .addGroup(grupoHLayout.createSequentialGroup()
                        .addGroup(grupoHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uruguai)
                            .addComponent(gana))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(H)
                        .addGap(15, 15, 15))))
        );
        grupoHLayout.setVerticalGroup(
            grupoHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupoHLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(portugual)
                .addGroup(grupoHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(grupoHLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gana)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(uruguai))
                    .addGroup(grupoHLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(H)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coreiaDoSul)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        quartas3.setBackground(new java.awt.Color(51, 51, 51));
        quartas3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        quartas3.setPreferredSize(new java.awt.Dimension(170, 216));

        quartasCUm.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        quartasCUm.setForeground(new java.awt.Color(255, 255, 255));

        quartasCDois.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        quartasCDois.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout quartas3Layout = new javax.swing.GroupLayout(quartas3);
        quartas3.setLayout(quartas3Layout);
        quartas3Layout.setHorizontalGroup(
            quartas3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quartas3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(quartas3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quartasCUm)
                    .addComponent(quartasCDois))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        quartas3Layout.setVerticalGroup(
            quartas3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quartas3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quartasCUm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quartasCDois)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        final1.setBackground(new java.awt.Color(51, 51, 51));
        final1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        final1.setPreferredSize(new java.awt.Dimension(170, 216));

        finalTimeUm.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        finalTimeUm.setForeground(new java.awt.Color(255, 255, 255));

        finalTimeDois.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        finalTimeDois.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout final1Layout = new javax.swing.GroupLayout(final1);
        final1.setLayout(final1Layout);
        final1Layout.setHorizontalGroup(
            final1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(final1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(final1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(finalTimeUm)
                    .addComponent(finalTimeDois))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        final1Layout.setVerticalGroup(
            final1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, final1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(finalTimeUm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finalTimeDois)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        grupoA.setBackground(new java.awt.Color(51, 51, 51));
        grupoA.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        grupoA.setPreferredSize(new java.awt.Dimension(170, 216));

        A.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        A.setForeground(new java.awt.Color(255, 255, 255));
        A.setText("A");

        qatar.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        qatar.setForeground(new java.awt.Color(255, 255, 255));
        qatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seleções/qatar_icon_127877.png"))); // NOI18N

        equador.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        equador.setForeground(new java.awt.Color(255, 255, 255));
        equador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seleções/ecuador_icon_127819.png"))); // NOI18N

        senegal.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        senegal.setForeground(new java.awt.Color(255, 255, 255));
        senegal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seleções/senegal_icon_127802.png"))); // NOI18N

        holanda.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        holanda.setForeground(new java.awt.Color(255, 255, 255));
        holanda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seleções/netherlands_icon_127838.png"))); // NOI18N

        javax.swing.GroupLayout grupoALayout = new javax.swing.GroupLayout(grupoA);
        grupoA.setLayout(grupoALayout);
        grupoALayout.setHorizontalGroup(
            grupoALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, grupoALayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(A)
                .addGap(18, 18, 18)
                .addGroup(grupoALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(holanda)
                    .addComponent(senegal)
                    .addComponent(equador)
                    .addComponent(qatar))
                .addContainerGap())
        );
        grupoALayout.setVerticalGroup(
            grupoALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, grupoALayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(qatar)
                .addGroup(grupoALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(grupoALayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(equador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(senegal))
                    .addGroup(grupoALayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(A)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(holanda)
                .addContainerGap())
        );

        oitavas7.setBackground(new java.awt.Color(51, 51, 51));
        oitavas7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        oitavas7.setPreferredSize(new java.awt.Dimension(170, 216));

        oitavasGrupoG1.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        oitavasGrupoG1.setForeground(new java.awt.Color(255, 255, 255));

        oitavasGrupoG2.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        oitavasGrupoG2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout oitavas7Layout = new javax.swing.GroupLayout(oitavas7);
        oitavas7.setLayout(oitavas7Layout);
        oitavas7Layout.setHorizontalGroup(
            oitavas7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oitavas7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(oitavas7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(oitavasGrupoG1)
                    .addComponent(oitavasGrupoG2))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        oitavas7Layout.setVerticalGroup(
            oitavas7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, oitavas7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(oitavasGrupoG1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oitavasGrupoG2)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        grupoE.setBackground(new java.awt.Color(51, 51, 51));
        grupoE.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        grupoE.setPreferredSize(new java.awt.Dimension(170, 216));

        E.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        E.setForeground(new java.awt.Color(255, 255, 255));
        E.setText("E");

        espanha.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        espanha.setForeground(new java.awt.Color(255, 255, 255));
        espanha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seleções/spain_icon_127825.png"))); // NOI18N

        costaRica.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        costaRica.setForeground(new java.awt.Color(255, 255, 255));
        costaRica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seleções/costa_rica_icon_127928.png"))); // NOI18N

        alemanha.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        alemanha.setForeground(new java.awt.Color(255, 255, 255));
        alemanha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seleções/Germany_29761.png"))); // NOI18N

        japao.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        japao.setForeground(new java.awt.Color(255, 255, 255));
        japao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seleções/jpjapanflag_111832.png"))); // NOI18N

        javax.swing.GroupLayout grupoELayout = new javax.swing.GroupLayout(grupoE);
        grupoE.setLayout(grupoELayout);
        grupoELayout.setHorizontalGroup(
            grupoELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupoELayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(grupoELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(grupoELayout.createSequentialGroup()
                        .addComponent(japao)
                        .addGap(0, 114, Short.MAX_VALUE))
                    .addGroup(grupoELayout.createSequentialGroup()
                        .addGroup(grupoELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(espanha)
                            .addGroup(grupoELayout.createSequentialGroup()
                                .addGroup(grupoELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(costaRica)
                                    .addComponent(alemanha))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(E)))
                        .addContainerGap())))
        );
        grupoELayout.setVerticalGroup(
            grupoELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupoELayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(espanha)
                .addGroup(grupoELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(grupoELayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(costaRica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alemanha, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(grupoELayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(E)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(japao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        oitavas3.setBackground(new java.awt.Color(51, 51, 51));
        oitavas3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        oitavas3.setPreferredSize(new java.awt.Dimension(170, 216));

        oitavasGrupoC1.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        oitavasGrupoC1.setForeground(new java.awt.Color(255, 255, 255));

        oitavasGrupoC2.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        oitavasGrupoC2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout oitavas3Layout = new javax.swing.GroupLayout(oitavas3);
        oitavas3.setLayout(oitavas3Layout);
        oitavas3Layout.setHorizontalGroup(
            oitavas3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oitavas3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(oitavas3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(oitavasGrupoC1)
                    .addComponent(oitavasGrupoC2))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        oitavas3Layout.setVerticalGroup(
            oitavas3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, oitavas3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(oitavasGrupoC1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oitavasGrupoC2)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        quartas4.setBackground(new java.awt.Color(51, 51, 51));
        quartas4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        quartas4.setPreferredSize(new java.awt.Dimension(170, 216));

        quartasDUm.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        quartasDUm.setForeground(new java.awt.Color(255, 255, 255));

        quartasDDois.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        quartasDDois.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout quartas4Layout = new javax.swing.GroupLayout(quartas4);
        quartas4.setLayout(quartas4Layout);
        quartas4Layout.setHorizontalGroup(
            quartas4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quartas4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(quartas4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quartasDUm)
                    .addComponent(quartasDDois))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        quartas4Layout.setVerticalGroup(
            quartas4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quartas4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quartasDUm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quartasDDois)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        oitavas8.setBackground(new java.awt.Color(51, 51, 51));
        oitavas8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        oitavas8.setPreferredSize(new java.awt.Dimension(170, 216));

        oitavasGrupoH1.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        oitavasGrupoH1.setForeground(new java.awt.Color(255, 255, 255));

        oitavasGrupoH2.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        oitavasGrupoH2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout oitavas8Layout = new javax.swing.GroupLayout(oitavas8);
        oitavas8.setLayout(oitavas8Layout);
        oitavas8Layout.setHorizontalGroup(
            oitavas8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oitavas8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(oitavas8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(oitavasGrupoH1)
                    .addComponent(oitavasGrupoH2))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        oitavas8Layout.setVerticalGroup(
            oitavas8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, oitavas8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(oitavasGrupoH1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oitavasGrupoH2)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        oitavas4.setBackground(new java.awt.Color(51, 51, 51));
        oitavas4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        oitavas4.setPreferredSize(new java.awt.Dimension(170, 216));

        oitavasGrupoD1.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        oitavasGrupoD1.setForeground(new java.awt.Color(255, 255, 255));

        oitavasGrupoD2.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        oitavasGrupoD2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout oitavas4Layout = new javax.swing.GroupLayout(oitavas4);
        oitavas4.setLayout(oitavas4Layout);
        oitavas4Layout.setHorizontalGroup(
            oitavas4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oitavas4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(oitavas4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(oitavasGrupoD1)
                    .addComponent(oitavasGrupoD2))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        oitavas4Layout.setVerticalGroup(
            oitavas4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, oitavas4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(oitavasGrupoD1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oitavasGrupoD2)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jLabel83.setFont(new java.awt.Font("Ubuntu Mono", 0, 18)); // NOI18N
        jLabel83.setForeground(new java.awt.Color(255, 255, 255));
        jLabel83.setText("OITAVAS");

        jLabel104.setFont(new java.awt.Font("Ubuntu Mono", 0, 18)); // NOI18N
        jLabel104.setForeground(new java.awt.Color(255, 255, 255));
        jLabel104.setText("SEMIFINAL");

        grupoB.setBackground(new java.awt.Color(51, 51, 51));
        grupoB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        grupoB.setPreferredSize(new java.awt.Dimension(170, 216));

        B.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        B.setForeground(new java.awt.Color(255, 255, 255));
        B.setText("B");

        inglaterra.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        inglaterra.setForeground(new java.awt.Color(255, 255, 255));
        inglaterra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seleções/gbengenglandflag_111695.png"))); // NOI18N

        ira.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        ira.setForeground(new java.awt.Color(255, 255, 255));
        ira.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seleções/iran_icon_127909.png"))); // NOI18N

        usa.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        usa.setForeground(new java.awt.Color(255, 255, 255));
        usa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seleções/united_states_icon_127943.png"))); // NOI18N

        gales.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        gales.setForeground(new java.awt.Color(255, 255, 255));
        gales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seleções/gbwlswalesflag_111786.png"))); // NOI18N

        javax.swing.GroupLayout grupoBLayout = new javax.swing.GroupLayout(grupoB);
        grupoB.setLayout(grupoBLayout);
        grupoBLayout.setHorizontalGroup(
            grupoBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupoBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(B)
                .addGap(15, 15, 15)
                .addGroup(grupoBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gales)
                    .addComponent(ira)
                    .addComponent(inglaterra)
                    .addComponent(usa))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        grupoBLayout.setVerticalGroup(
            grupoBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupoBLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(inglaterra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(grupoBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(grupoBLayout.createSequentialGroup()
                        .addComponent(ira)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, grupoBLayout.createSequentialGroup()
                        .addComponent(B)
                        .addGap(20, 20, 20)))
                .addComponent(gales)
                .addContainerGap())
        );

        jLabel105.setFont(new java.awt.Font("Ubuntu Mono", 0, 18)); // NOI18N
        jLabel105.setForeground(new java.awt.Color(255, 255, 255));
        jLabel105.setText("QUARTAS");

        jLabel116.setFont(new java.awt.Font("Ubuntu Mono", 0, 18)); // NOI18N
        jLabel116.setForeground(new java.awt.Color(255, 255, 255));
        jLabel116.setText("QUARTAS");

        grupoF.setBackground(new java.awt.Color(51, 51, 51));
        grupoF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        grupoF.setPreferredSize(new java.awt.Dimension(170, 216));

        F.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        F.setForeground(new java.awt.Color(255, 255, 255));
        F.setText("F");

        belgica.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        belgica.setForeground(new java.awt.Color(255, 255, 255));
        belgica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seleções/belgium_icon_127865.png"))); // NOI18N

        canada.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        canada.setForeground(new java.awt.Color(255, 255, 255));
        canada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seleções/canada_icon_127925.png"))); // NOI18N

        marracos.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        marracos.setForeground(new java.awt.Color(255, 255, 255));
        marracos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seleções/morocco_icon_127773.png"))); // NOI18N

        croacia.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        croacia.setForeground(new java.awt.Color(255, 255, 255));
        croacia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seleções/croatia_icon_127840.png"))); // NOI18N

        javax.swing.GroupLayout grupoFLayout = new javax.swing.GroupLayout(grupoF);
        grupoF.setLayout(grupoFLayout);
        grupoFLayout.setHorizontalGroup(
            grupoFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupoFLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(grupoFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(grupoFLayout.createSequentialGroup()
                        .addGroup(grupoFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(belgica)
                            .addComponent(croacia))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(grupoFLayout.createSequentialGroup()
                        .addGroup(grupoFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(canada)
                            .addComponent(marracos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addComponent(F)
                        .addGap(17, 17, 17))))
        );
        grupoFLayout.setVerticalGroup(
            grupoFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupoFLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(belgica)
                .addGroup(grupoFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(grupoFLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(canada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(marracos))
                    .addGroup(grupoFLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(F)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(croacia)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel117.setFont(new java.awt.Font("Ubuntu Mono", 0, 18)); // NOI18N
        jLabel117.setForeground(new java.awt.Color(255, 255, 255));
        jLabel117.setText("FINAL");

        jLabel25.setFont(new java.awt.Font("Ubuntu Mono", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("OITAVAS");

        jLabel118.setFont(new java.awt.Font("Ubuntu Mono", 0, 18)); // NOI18N
        jLabel118.setForeground(new java.awt.Color(255, 255, 255));
        jLabel118.setText("SEMIFINAL");

        sair.setForeground(new java.awt.Color(255, 0, 0));
        sair.setText("SAIR");
        sair.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });

        simular.setText("SIMULAR JOGOS");
        simular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simularActionPerformed(evt);
            }
        });

        quartas1.setBackground(new java.awt.Color(51, 51, 51));
        quartas1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        quartas1.setPreferredSize(new java.awt.Dimension(170, 216));

        quartasAUm.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        quartasAUm.setForeground(new java.awt.Color(255, 255, 255));

        quartasADois.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        quartasADois.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout quartas1Layout = new javax.swing.GroupLayout(quartas1);
        quartas1.setLayout(quartas1Layout);
        quartas1Layout.setHorizontalGroup(
            quartas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quartas1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(quartas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quartasAUm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(quartasADois, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                .addContainerGap())
        );
        quartas1Layout.setVerticalGroup(
            quartas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quartas1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quartasAUm, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(quartasADois, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        semifinal1.setBackground(new java.awt.Color(51, 51, 51));
        semifinal1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        semifinal1.setPreferredSize(new java.awt.Dimension(170, 216));

        semifinalAUm.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        semifinalAUm.setForeground(new java.awt.Color(255, 255, 255));

        semifinalADois.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        semifinalADois.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout semifinal1Layout = new javax.swing.GroupLayout(semifinal1);
        semifinal1.setLayout(semifinal1Layout);
        semifinal1Layout.setHorizontalGroup(
            semifinal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(semifinal1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(semifinal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(semifinalAUm)
                    .addComponent(semifinalADois))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        semifinal1Layout.setVerticalGroup(
            semifinal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, semifinal1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(semifinalAUm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(semifinalADois)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        grupoC.setBackground(new java.awt.Color(51, 51, 51));
        grupoC.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        grupoC.setPreferredSize(new java.awt.Dimension(170, 216));

        C.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        C.setForeground(new java.awt.Color(255, 255, 255));
        C.setText("C");

        argentina.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        argentina.setForeground(new java.awt.Color(255, 255, 255));
        argentina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seleções/argentina_icon_127814.png"))); // NOI18N

        arabiaSaudita.setBackground(new java.awt.Color(255, 255, 255));
        arabiaSaudita.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        arabiaSaudita.setForeground(new java.awt.Color(255, 255, 255));
        arabiaSaudita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seleções/saudi_arabia_icon_127908.png"))); // NOI18N

        mexico.setBackground(new java.awt.Color(255, 255, 255));
        mexico.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        mexico.setForeground(new java.awt.Color(255, 255, 255));
        mexico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seleções/mexico_icon_127947.png"))); // NOI18N

        polonia.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        polonia.setForeground(new java.awt.Color(255, 255, 255));
        polonia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seleções/poland_icon_127852.png"))); // NOI18N

        javax.swing.GroupLayout grupoCLayout = new javax.swing.GroupLayout(grupoC);
        grupoC.setLayout(grupoCLayout);
        grupoCLayout.setHorizontalGroup(
            grupoCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, grupoCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(C)
                .addGap(13, 13, 13)
                .addGroup(grupoCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(arabiaSaudita)
                    .addComponent(mexico, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(polonia, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(argentina, javax.swing.GroupLayout.Alignment.LEADING)))
        );
        grupoCLayout.setVerticalGroup(
            grupoCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grupoCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(argentina)
                .addGroup(grupoCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(grupoCLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(arabiaSaudita)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mexico))
                    .addGroup(grupoCLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(C)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(polonia)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        oitavas5.setBackground(new java.awt.Color(51, 51, 51));
        oitavas5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        oitavas5.setPreferredSize(new java.awt.Dimension(170, 216));

        oitavasGrupoE1.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        oitavasGrupoE1.setForeground(new java.awt.Color(255, 255, 255));

        oitavasGrupoE2.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        oitavasGrupoE2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout oitavas5Layout = new javax.swing.GroupLayout(oitavas5);
        oitavas5.setLayout(oitavas5Layout);
        oitavas5Layout.setHorizontalGroup(
            oitavas5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oitavas5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(oitavas5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(oitavasGrupoE1)
                    .addComponent(oitavasGrupoE2))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        oitavas5Layout.setVerticalGroup(
            oitavas5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, oitavas5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(oitavasGrupoE1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oitavasGrupoE2)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        oitavas1.setBackground(new java.awt.Color(51, 51, 51));
        oitavas1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        oitavas1.setPreferredSize(new java.awt.Dimension(170, 216));

        oitavasGrupoA1.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        oitavasGrupoA1.setForeground(new java.awt.Color(255, 255, 255));

        oitavasGrupoA2.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        oitavasGrupoA2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout oitavas1Layout = new javax.swing.GroupLayout(oitavas1);
        oitavas1.setLayout(oitavas1Layout);
        oitavas1Layout.setHorizontalGroup(
            oitavas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oitavas1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(oitavas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(oitavasGrupoA1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(oitavasGrupoA2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        oitavas1Layout.setVerticalGroup(
            oitavas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, oitavas1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(oitavasGrupoA1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(oitavasGrupoA2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        quartas2.setBackground(new java.awt.Color(51, 51, 51));
        quartas2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        quartas2.setPreferredSize(new java.awt.Dimension(170, 216));

        quartasBUm.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        quartasBUm.setForeground(new java.awt.Color(255, 255, 255));

        quartasBDois.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        quartasBDois.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout quartas2Layout = new javax.swing.GroupLayout(quartas2);
        quartas2.setLayout(quartas2Layout);
        quartas2Layout.setHorizontalGroup(
            quartas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quartas2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(quartas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quartasBUm)
                    .addComponent(quartasBDois))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        quartas2Layout.setVerticalGroup(
            quartas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quartas2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quartasBUm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quartasBDois)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        oitavas6.setBackground(new java.awt.Color(51, 51, 51));
        oitavas6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        oitavas6.setPreferredSize(new java.awt.Dimension(170, 216));

        oitavasGrupoF1.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        oitavasGrupoF1.setForeground(new java.awt.Color(255, 255, 255));

        oitavasGrupoF2.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        oitavasGrupoF2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout oitavas6Layout = new javax.swing.GroupLayout(oitavas6);
        oitavas6.setLayout(oitavas6Layout);
        oitavas6Layout.setHorizontalGroup(
            oitavas6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oitavas6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(oitavas6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(oitavasGrupoF1)
                    .addComponent(oitavasGrupoF2))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        oitavas6Layout.setVerticalGroup(
            oitavas6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, oitavas6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(oitavasGrupoF1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oitavasGrupoF2)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        oitavas2.setBackground(new java.awt.Color(51, 51, 51));
        oitavas2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        oitavas2.setPreferredSize(new java.awt.Dimension(170, 216));

        oitavasGrupoB1.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        oitavasGrupoB1.setForeground(new java.awt.Color(255, 255, 255));

        oitavasGrupoB2.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        oitavasGrupoB2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout oitavas2Layout = new javax.swing.GroupLayout(oitavas2);
        oitavas2.setLayout(oitavas2Layout);
        oitavas2Layout.setHorizontalGroup(
            oitavas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oitavas2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(oitavas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(oitavasGrupoB1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(oitavasGrupoB2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        oitavas2Layout.setVerticalGroup(
            oitavas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, oitavas2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(oitavasGrupoB1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(oitavasGrupoB2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        campeao.setBackground(new java.awt.Color(51, 51, 51));
        campeao.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        campeao.setPreferredSize(new java.awt.Dimension(170, 216));

        timeCampeao.setFont(new java.awt.Font("Ubuntu Mono", 1, 14)); // NOI18N
        timeCampeao.setForeground(new java.awt.Color(255, 255, 255));
        timeCampeao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/world-cup.png"))); // NOI18N

        javax.swing.GroupLayout campeaoLayout = new javax.swing.GroupLayout(campeao);
        campeao.setLayout(campeaoLayout);
        campeaoLayout.setHorizontalGroup(
            campeaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(campeaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(timeCampeao, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        campeaoLayout.setVerticalGroup(
            campeaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(campeaoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(timeCampeao, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(grupoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(grupoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(grupoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(grupoD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(oitavas1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                            .addComponent(oitavas2, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                            .addComponent(oitavas4, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                            .addComponent(oitavas3, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(73, 73, 73)
                                        .addComponent(jLabel25)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(48, 48, 48)
                                                        .addComponent(jLabel116))
                                                    .addComponent(quartas2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(quartas1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel105)
                                                .addGap(63, 63, 63)
                                                .addComponent(oitavas5, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(80, 80, 80)
                                                        .addComponent(semifinal1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(131, 131, 131)
                                                        .addComponent(jLabel118)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(jLabel104)
                                                        .addGap(108, 108, 108)
                                                        .addComponent(oitavas6, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(semifinal2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(79, 79, 79))
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                    .addComponent(quartas3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addComponent(quartas4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(oitavas8, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(oitavas7, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel83)
                                        .addGap(57, 57, 57)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(grupoH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(grupoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(grupoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(grupoG, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(397, 397, 397)
                                .addComponent(simular, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel117)
                                .addGap(175, 175, 175))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(final1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(106, 106, 106)))
                        .addComponent(campeao, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(166, 166, 166)
                        .addComponent(sair, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sair, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel117))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(final1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(campeao, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(oitavas1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(grupoA, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(grupoB, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(oitavas6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(oitavas2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(grupoC, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(oitavas3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(43, 43, 43)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(grupoD, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(24, 24, 24)
                                                .addComponent(oitavas4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(oitavas7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(47, 47, 47)
                                        .addComponent(oitavas8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel83)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(oitavas5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(grupoE, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(grupoF, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(grupoG, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(grupoH, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(58, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel105, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel116, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(quartas1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quartas3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel104)
                            .addComponent(jLabel118))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(semifinal2, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                    .addComponent(semifinal1, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                                .addGap(49, 49, 49)
                                .addComponent(quartas2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(quartas4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(simular, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        this.dispose();
    }//GEN-LAST:event_sairActionPerformed

    private void simularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simularActionPerformed
        SimulacaoCode simularFase = new SimulacaoCode();
        
        ArrayList<String> grupoA = simularFase.faseDeGrupos(simularFase.grupoA);
        ArrayList<String> grupoB = simularFase.faseDeGrupos(simularFase.grupoB);
        ArrayList<String> grupoC = simularFase.faseDeGrupos(simularFase.grupoC);
        ArrayList<String> grupoD = simularFase.faseDeGrupos(simularFase.grupoD);
        ArrayList<String> grupoE = simularFase.faseDeGrupos(simularFase.grupoE);
        ArrayList<String> grupoF = simularFase.faseDeGrupos(simularFase.grupoF);
        ArrayList<String> grupoG = simularFase.faseDeGrupos(simularFase.grupoG);
        ArrayList<String> grupoH = simularFase.faseDeGrupos(simularFase.grupoH);
        
        ArrayList<String> oitavasPartidaUm = simularFase.partidas(grupoA.get(0), grupoB.get(1));
        ArrayList<String> oitavasPartidaDois = simularFase.partidas(grupoC.get(0), grupoD.get(1));
        ArrayList<String> oitavasPartidaTres = simularFase.partidas(grupoE.get(0), grupoF.get(1));
        ArrayList<String> oitavasPartidaQuatro = simularFase.partidas(grupoG.get(0), grupoH.get(1));
        ArrayList<String> oitavasPartidaCinco = simularFase.partidas(grupoB.get(0), grupoA.get(1));
        ArrayList<String> oitavasPartidaSeis = simularFase.partidas(grupoD.get(0), grupoC.get(1));
        ArrayList<String> oitavasPartidaSete = simularFase.partidas(grupoF.get(0), grupoE.get(1));
        ArrayList<String> oitavasPartidaOito = simularFase.partidas(grupoH.get(0), grupoG.get(1));
        
        
        ArrayList<String> quartasPartidaUm = simularFase.partidas(oitavasPartidaUm.get(0), oitavasPartidaDois.get(0));
        ArrayList<String> quartasPartidaDois = simularFase.partidas(oitavasPartidaTres.get(0), oitavasPartidaQuatro.get(0));
        ArrayList<String> quartasPartidaTres = simularFase.partidas(oitavasPartidaCinco.get(0), oitavasPartidaSeis.get(0));
        ArrayList<String> quartasPartidaQuatro = simularFase.partidas(oitavasPartidaSete.get(0), oitavasPartidaOito.get(0));
        
        
        ArrayList<String> semifinalUm = simularFase.partidas(quartasPartidaUm.get(0), quartasPartidaDois.get(0));
        ArrayList<String> semifinalDois = simularFase.partidas(quartasPartidaTres.get(0), quartasPartidaQuatro.get(0));
        
        ArrayList<String> finals = simularFase.partidas(semifinalUm.get(0), semifinalDois.get(0));
        
   
        
        
        oitavasGrupoA1.setText(grupoA.get(0) + "  " + oitavasPartidaUm.get(1));
        oitavasGrupoA2.setText(grupoB.get(1) + "  " + oitavasPartidaUm.get(2));
       
        oitavasGrupoB1.setText(grupoC.get(0) + "  " + oitavasPartidaDois.get(1));
        oitavasGrupoB2.setText(grupoD.get(1) + "  " + oitavasPartidaDois.get(2));
        
        
        oitavasGrupoC1.setText(grupoE.get(0) + "  " + oitavasPartidaTres.get(1));
        oitavasGrupoC2.setText(grupoF.get(1) + "  " + oitavasPartidaTres.get(2));
        
        
        oitavasGrupoD1.setText(grupoG.get(0) + "  " + oitavasPartidaQuatro.get(1));
        oitavasGrupoD2.setText(grupoH.get(1) + "  " + oitavasPartidaQuatro.get(2));
        
        
        oitavasGrupoE1.setText(grupoB.get(0) + "  " + oitavasPartidaCinco.get(1));
        oitavasGrupoE2.setText(grupoA.get(1) + "  " + oitavasPartidaCinco.get(2));
        
        
        oitavasGrupoF1.setText(grupoD.get(0) + "  " + oitavasPartidaSeis.get(1));
        oitavasGrupoF2.setText(grupoC.get(1) + "  " + oitavasPartidaSeis.get(2));
        
        
        oitavasGrupoG1.setText(grupoF.get(0) + "  " + oitavasPartidaSete.get(1));
        oitavasGrupoG2.setText(grupoE.get(1) + "  " + oitavasPartidaSete.get(2));
        
        
        oitavasGrupoH1.setText(grupoH.get(0) + "  " + oitavasPartidaOito.get(1));
        oitavasGrupoH2.setText(grupoG.get(1) + "  " + oitavasPartidaOito.get(2));
        
        
        
        
        
        quartasAUm.setText(oitavasPartidaUm.get(0) + "  " + quartasPartidaUm.get(1));
        quartasADois.setText(oitavasPartidaDois.get(0) + "  " + quartasPartidaUm.get(2));
        
        quartasBUm.setText(oitavasPartidaTres.get(0) + "  " + quartasPartidaDois.get(1));
        quartasBDois.setText(oitavasPartidaQuatro.get(0) + "  " + quartasPartidaDois.get(2));     
        
        quartasCUm.setText(oitavasPartidaCinco.get(0) + "  " + quartasPartidaTres.get(1));
        quartasCDois.setText(oitavasPartidaSeis.get(0) + "  " + quartasPartidaTres.get(2));

        quartasDUm.setText(oitavasPartidaSete.get(0) + "  " + quartasPartidaQuatro.get(1));
        quartasDDois.setText(oitavasPartidaOito.get(0) + "  " + quartasPartidaQuatro.get(2));      
        
        
        
        
        
        semifinalAUm.setText(quartasPartidaUm.get(0) + "  " + semifinalUm.get(1));
        semifinalADois.setText(quartasPartidaDois.get(0) + "  " + semifinalUm.get(2));
        
        
        semifinalBUm.setText(quartasPartidaTres.get(0) + "  " + semifinalDois.get(1));
        semifinalBDois.setText(quartasPartidaQuatro.get(0) + "  " + semifinalDois.get(2));

      
        
        finalTimeUm.setText(semifinalUm.get(0) + "  " + finals.get(1));
        finalTimeDois.setText(semifinalDois.get(0) + "  " + finals.get(2));        
                
        
        timeCampeao.setText(finals.get(0));
        
        
        
     
       
        
    }//GEN-LAST:event_simularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simulacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simulacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simulacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simulacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Simulacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A;
    private javax.swing.JLabel B;
    private javax.swing.JLabel C;
    private javax.swing.JLabel D;
    private javax.swing.JLabel E;
    private javax.swing.JLabel F;
    private javax.swing.JLabel G;
    private javax.swing.JLabel H;
    private javax.swing.JLabel alemanha;
    private javax.swing.JLabel arabiaSaudita;
    private javax.swing.JLabel argentina;
    private javax.swing.JLabel australia;
    private javax.swing.JLabel belgica;
    private javax.swing.JLabel brasil;
    private javax.swing.JLabel camaroes;
    private javax.swing.JPanel campeao;
    private javax.swing.JLabel canada;
    private javax.swing.JLabel coreiaDoSul;
    private javax.swing.JLabel costaRica;
    private javax.swing.JLabel croacia;
    private javax.swing.JLabel dinamarca;
    private javax.swing.JLabel equador;
    private javax.swing.JLabel espanha;
    private javax.swing.JPanel final1;
    private javax.swing.JLabel finalTimeDois;
    private javax.swing.JLabel finalTimeUm;
    private javax.swing.JLabel franca;
    private javax.swing.JLabel gales;
    private javax.swing.JLabel gana;
    private javax.swing.JPanel grupoA;
    private javax.swing.JPanel grupoB;
    private javax.swing.JPanel grupoC;
    private javax.swing.JPanel grupoD;
    private javax.swing.JPanel grupoE;
    private javax.swing.JPanel grupoF;
    private javax.swing.JPanel grupoG;
    private javax.swing.JPanel grupoH;
    private javax.swing.JLabel holanda;
    private javax.swing.JLabel inglaterra;
    private javax.swing.JLabel ira;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel japao;
    private javax.swing.JLabel marracos;
    private javax.swing.JLabel mexico;
    private javax.swing.JPanel oitavas1;
    private javax.swing.JPanel oitavas2;
    private javax.swing.JPanel oitavas3;
    private javax.swing.JPanel oitavas4;
    private javax.swing.JPanel oitavas5;
    private javax.swing.JPanel oitavas6;
    private javax.swing.JPanel oitavas7;
    private javax.swing.JPanel oitavas8;
    private javax.swing.JLabel oitavasGrupoA1;
    private javax.swing.JLabel oitavasGrupoA2;
    private javax.swing.JLabel oitavasGrupoB1;
    private javax.swing.JLabel oitavasGrupoB2;
    private javax.swing.JLabel oitavasGrupoC1;
    private javax.swing.JLabel oitavasGrupoC2;
    private javax.swing.JLabel oitavasGrupoD1;
    private javax.swing.JLabel oitavasGrupoD2;
    private javax.swing.JLabel oitavasGrupoE1;
    private javax.swing.JLabel oitavasGrupoE2;
    private javax.swing.JLabel oitavasGrupoF1;
    private javax.swing.JLabel oitavasGrupoF2;
    private javax.swing.JLabel oitavasGrupoG1;
    private javax.swing.JLabel oitavasGrupoG2;
    private javax.swing.JLabel oitavasGrupoH1;
    private javax.swing.JLabel oitavasGrupoH2;
    private javax.swing.JLabel polonia;
    private javax.swing.JLabel portugual;
    private javax.swing.JLabel qatar;
    private javax.swing.JPanel quartas1;
    private javax.swing.JPanel quartas2;
    private javax.swing.JPanel quartas3;
    private javax.swing.JPanel quartas4;
    private javax.swing.JLabel quartasADois;
    private javax.swing.JLabel quartasAUm;
    private javax.swing.JLabel quartasBDois;
    private javax.swing.JLabel quartasBUm;
    private javax.swing.JLabel quartasCDois;
    private javax.swing.JLabel quartasCUm;
    private javax.swing.JLabel quartasDDois;
    private javax.swing.JLabel quartasDUm;
    private code.Botao sair;
    private javax.swing.JPanel semifinal1;
    private javax.swing.JPanel semifinal2;
    private javax.swing.JLabel semifinalADois;
    private javax.swing.JLabel semifinalAUm;
    private javax.swing.JLabel semifinalBDois;
    private javax.swing.JLabel semifinalBUm;
    private javax.swing.JLabel senegal;
    private javax.swing.JLabel servia;
    private javax.swing.JButton simular;
    private javax.swing.JLabel suica;
    private javax.swing.JLabel timeCampeao;
    private javax.swing.JLabel tunisia;
    private javax.swing.JLabel uruguai;
    private javax.swing.JLabel usa;
    // End of variables declaration//GEN-END:variables

    public void GrupoOficial() {
        code.GruposOficiais simulacao = new code.GruposOficiais();
        qatar.setText(simulacao.grupoA[0]);
        equador.setText(simulacao.grupoA[1]);
        senegal.setText(simulacao.grupoA[2]);
        holanda.setText(simulacao.grupoA[3]);

        inglaterra.setText(simulacao.grupoB[0]);
        ira.setText(simulacao.grupoB[1]);
        usa.setText(simulacao.grupoB[2]);
        gales.setText(simulacao.grupoB[3]);

        argentina.setText(simulacao.grupoC[0]);
        arabiaSaudita.setText(simulacao.grupoC[1]);
        mexico.setText(simulacao.grupoC[2]);
        polonia.setText(simulacao.grupoC[3]);

        franca.setText(simulacao.grupoD[0]);
        australia.setText(simulacao.grupoD[1]);
        dinamarca.setText(simulacao.grupoD[2]);
        tunisia.setText(simulacao.grupoD[3]);

        espanha.setText(simulacao.grupoE[0]);
        costaRica.setText(simulacao.grupoE[1]);
        alemanha.setText(simulacao.grupoE[2]);
        japao.setText(simulacao.grupoE[3]);

        belgica.setText(simulacao.grupoF[0]);
        canada.setText(simulacao.grupoF[1]);
        marracos.setText(simulacao.grupoF[2]);
        croacia.setText(simulacao.grupoF[3]);

        brasil.setText(simulacao.grupoG[0]);
        servia.setText(simulacao.grupoG[1]);
        suica.setText(simulacao.grupoG[2]);
        camaroes.setText(simulacao.grupoG[3]);

        portugual.setText(simulacao.grupoH[0]);
        gana.setText(simulacao.grupoH[1]);
        uruguai.setText(simulacao.grupoH[2]);
        coreiaDoSul.setText(simulacao.grupoH[3]);
    }
    
    SelecoesDAO selecao = new SelecoesDAO();
    ArrayList<SelecoesDTO> lista = selecao.selecoesLista();
    
    public String grupoA2[] = {
        lista.get(8).toString(), //Catar
        lista.get(13).toString(), //Equador 
        lista.get(27).toString(), //Senegal
        lista.get(18).toString()}; //Holanda

    public String grupoB2[] = {
        lista.get(19).toString(), //Inglaterra
        lista.get(20).toString(), //Irã
        lista.get(15).toString(), //Estados Unidos
        lista.get(24).toString()}; //Pais de Gales

    public String grupoC2[] = {
        lista.get(2).toString(), //Argentina
        lista.get(1).toString(), //Arabia Saudita
        lista.get(23).toString(), //Mexico
        lista.get(25).toString()}; //Polonia

    public String grupoD2[] = {
        lista.get(16).toString(), //Franca
        lista.get(3).toString(), //Australia
        lista.get(12).toString(), //Dinamarca
        lista.get(30).toString()}; //Tunisia

    public String grupoE2[] = {
        lista.get(14).toString(), //Espanha
        lista.get(10).toString(), //Costa Rica
        lista.get(0).toString(), //Alemanha
        lista.get(21).toString()}; //Japao

    public String grupoF2[] = {
        lista.get(4).toString(), //Belgica
        lista.get(7).toString(), //Canada
        lista.get(22).toString(), //Marrocos
        lista.get(11).toString()}; //Croacia

    public String grupoG2[] = {
        lista.get(5).toString(), //Brasil
        lista.get(28).toString(), //Servia
        lista.get(29).toString(), //Suica
        lista.get(6).toString()}; //Camaroes

    public String grupoH2[] = {
        lista.get(26).toString(), //Portugal
        lista.get(17).toString(), //Gana
        lista.get(31).toString(), //Uruguai
        lista.get(9).toString()}; //Coreia do Sul


    
    
    
    
    
 
}
